<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" hash="3186869251">
    <data-source source="LOCAL" name="Django default" product="" version="" jdbc-version="" driver-name="" driver-version="" uuid="3eaaf0cd-ee9d-4ef4-b187-39b3fcbc1dbc">
      <jdbc-driver>com.mysql.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql:///C:\Users\Josko\Desktop\Python\ZED_Annalytics\db.zedAnalytic</jdbc-url>
      <user-name>josko</user-name>
      <user-password>df9bdfcbdfd8dfcbdfcddfc5dfc4df9b</user-password>
      <libraries>
        <library>
          <url>file://$USER_HOME$/.PyCharm20/config/jdbc-drivers/mysql-connector-license.txt</url>
        </library>
        <library>
          <url>file://$USER_HOME$/.PyCharm20/config/jdbc-drivers/mysql-connector-java-5.1.26-bin.jar</url>
        </library>
      </libraries>
    </data-source>
  </component>
</project>

